apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-deployment
  template:
    metadata:
      labels:
        app: webapp-deployment
    spec:
      containers:
      - name: webapp
        image: registry.digitalocean.com/loukas-tech-container-registry/webapp:latest
        envFrom:
          - secretRef:
              name: django-webapp-prod-env
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: loukas-tech-container-registry

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: webapp-deployment