name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: ./.github/workflows/test-django.yaml
  build_job:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CONTAINER_WEBAPP_WORKDIR: /home/webapp
      DJANGO_PROJECT_SUBDIR: loukas_tech
      WEBAPP_PORT: 8000
      MY_REGISTRY: registry.digitalocean.com/loukas-tech-container-registry
      CLUSTER_NAME: k8s-fra1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Build container image
        working-directory: ./webapp
        run: |
           docker build -f Dockerfile \
             -t ${MY_REGISTRY}/webapp:latest  \
             -t ${MY_REGISTRY}/webapp:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
             --build-arg CONTAINER_WEBAPP_WORKDIR="${CONTAINER_WEBAPP_WORKDIR}" \
             --build-arg DJANGO_PROJECT_SUBDIR="${DJANGO_PROJECT_SUBDIR}" \
             --build-arg WEBAPP_PORT="${WEBAPP_PORT}" \
             .
      - name: Push image
        run: |
          docker push ${MY_REGISTRY}/webapp --all-tags
      - name: K8s cluster kubeconfig file with/ short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      # - name: Update deployment secrets
      #   run: |
      #     cat << EOF >> web/.env.prod
      #     AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      #     DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      #     DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
      #     DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
      #     ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
      #     POSTGRES_DB=${{ secrets.POSTGRES_DB }}
      #     POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      #     POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      #     POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
      #     POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
      #     EOF
      #     kubectl delete secret django-k8s-web-prod-env
      #     kubectl create secret generic django-k8s-web-prod-env --from-env-file=web/.env.prod
      - name: Update Deployment image
        run: |
          kubectl set image deployment/webapp-deployment webapp=${MY_REGISTRY}/webapp:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/webapp-deployment
      - name: Post-build Django Commands - Migrate / Collectstatic
        run: |
          kubectl get pods --selector=app=webapp-deployment --output=jsonpath='{.items[0].metadata.name}' --field-selector=status.phase=Running
          export SINGLE_POD_NAME=$(kubectl get pods --selector=app=webapp-deployment --output=jsonpath='{.items[0].metadata.name}' --field-selector=status.phase=Running)
          echo $SINGLE_POD_NAME
          kubectl exec -it $SINGLE_POD_NAME -- bash ${CONTAINER_WEBAPP_WORKDIR}/migrate.sh
          kubectl exec -it $SINGLE_POD_NAME -- bash ${CONTAINER_WEBAPP_WORKDIR}/collectstatic.sh