name: test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_job:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Update deployment secrets
        run: |                                   
          cat << EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: django-webapp-prod-env
          stringData:
            x=1
            x=2
          EOF
